name: Reddit Streak
on:
    schedule:
        - cron: '0 */12 * * *'
    workflow_dispatch:

jobs:
    run-bot:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '20'

            - name: Install Dependencies
              run: npm install

            - name: Install Chrome Dependencies
              run: sudo apt-get update && sudo apt-get install -y libgbm-dev wget gnupg xvfb

            - name: Make Screenshots Directory
              run: mkdir screenshots

            - name: Run Script with Virtual Display
              env:
                  REDDIT_USERNAME: ${{ secrets.REDDIT_USERNAME }}
                  REDDIT_PASSWORD: ${{ secrets.REDDIT_PASSWORD }}
                  REDDIT_2FA_SECRET: ${{ secrets.REDDIT_2FA_SECRET }}
              run: xvfb-run --auto-servernum npm run dev
